-- Seed federal incentives data
INSERT INTO incentives (layer, name, description, dollar_amount, percentage_amount, max_amount, upgrade_categories, state_code, utility_name, income_threshold_type, home_types, ownership_required, stacking_rules, status, effective_date, expiration_date, claim_type, claim_steps, claim_url, source_url)
VALUES
  ('federal', '25C Heat Pump Tax Credit', 'Federal tax credit for qualifying heat pump installations. Claimed on your annual tax return.', NULL, 30, 2000, ARRAY['heat_pump'], NULL, NULL, 'none', ARRAY['single_family', 'condo', 'manufactured'], true, '{"combinable_with": ["state", "utility", "manufacturer"], "excluded_with": []}', 'active', '2023-01-01', '2032-12-31', 'tax_credit', ARRAY['Purchase qualifying heat pump', 'Get IRS Form 5695', 'File with your tax return'], 'https://www.irs.gov/credits-deductions/energy-efficient-home-improvement-credit', 'https://www.irs.gov'),
  ('federal', '25C Water Heater Tax Credit', 'Federal tax credit for heat pump water heaters meeting ENERGY STAR efficiency requirements.', NULL, 30, 2000, ARRAY['heat_pump_water_heater'], NULL, NULL, 'none', ARRAY['single_family', 'condo', 'manufactured'], true, '{"combinable_with": ["state", "utility", "manufacturer"], "excluded_with": []}', 'active', '2023-01-01', '2032-12-31', 'tax_credit', ARRAY['Purchase qualifying water heater', 'Get IRS Form 5695', 'File with your tax return'], 'https://www.irs.gov/credits-deductions/energy-efficient-home-improvement-credit', 'https://www.irs.gov'),
  ('federal', '25C Insulation & Air Sealing Credit', 'Federal tax credit for insulation and air sealing improvements that meet efficiency standards.', NULL, 30, 1200, ARRAY['insulation', 'weatherization'], NULL, NULL, 'none', ARRAY['single_family', 'condo', 'manufactured'], true, '{"combinable_with": ["state", "utility", "manufacturer"], "excluded_with": []}', 'active', '2023-01-01', '2032-12-31', 'tax_credit', ARRAY['Complete qualifying improvements', 'Keep receipts and certifications', 'File IRS Form 5695 with tax return'], 'https://www.irs.gov/credits-deductions/energy-efficient-home-improvement-credit', 'https://www.irs.gov'),
  ('federal', '25C Windows & Doors Credit', 'Federal tax credit for ENERGY STAR certified windows, skylights, and exterior doors.', NULL, 30, 600, ARRAY['windows'], NULL, NULL, 'none', ARRAY['single_family', 'condo', 'manufactured'], true, '{"combinable_with": ["state", "utility", "manufacturer"], "excluded_with": []}', 'active', '2023-01-01', '2032-12-31', 'tax_credit', ARRAY['Purchase ENERGY STAR certified products', 'Keep manufacturer certifications', 'File IRS Form 5695 with tax return'], 'https://www.irs.gov/credits-deductions/energy-efficient-home-improvement-credit', 'https://www.irs.gov'),
  ('federal', '25C Electrical Panel Credit', 'Federal tax credit for electrical panel upgrades that enable electrification.', NULL, 30, 600, ARRAY['electrical_panel'], NULL, NULL, 'none', ARRAY['single_family', 'condo', 'manufactured'], true, '{"combinable_with": ["state", "utility", "manufacturer"], "excluded_with": []}', 'active', '2023-01-01', '2032-12-31', 'tax_credit', ARRAY['Upgrade to 200-amp panel', 'Keep contractor invoices', 'File IRS Form 5695 with tax return'], 'https://www.irs.gov/credits-deductions/energy-efficient-home-improvement-credit', 'https://www.irs.gov'),
  ('federal', '25D Residential Clean Energy Credit (Solar)', 'Federal tax credit for residential solar panel installations. No maximum limit.', NULL, 30, NULL, ARRAY['solar'], NULL, NULL, 'none', ARRAY['single_family', 'condo', 'manufactured'], true, '{"combinable_with": ["state", "utility", "manufacturer"], "excluded_with": []}', 'active', '2023-01-01', '2034-12-31', 'tax_credit', ARRAY['Install qualifying solar system', 'Obtain Form 5695 from installer', 'Claim on federal tax return'], 'https://www.irs.gov/credits-deductions/residential-clean-energy-credit', 'https://www.irs.gov'),
  ('federal', '25D Residential Clean Energy Credit (Battery)', 'Federal tax credit for home battery storage systems 3 kWh or greater capacity.', NULL, 30, NULL, ARRAY['battery'], NULL, NULL, 'none', ARRAY['single_family', 'condo', 'manufactured'], true, '{"combinable_with": ["state", "utility", "manufacturer"], "excluded_with": []}', 'active', '2023-01-01', '2034-12-31', 'tax_credit', ARRAY['Install qualifying battery system', 'Obtain manufacturer specifications', 'Claim on federal tax return'], 'https://www.irs.gov/credits-deductions/residential-clean-energy-credit', 'https://www.irs.gov'),
  ('federal', '30C EV Charger Tax Credit', 'Federal tax credit for home EV charging equipment installation in eligible census tracts.', NULL, 30, 1000, ARRAY['ev_charger'], NULL, NULL, 'none', ARRAY['single_family', 'condo', 'manufactured'], true, '{"combinable_with": ["state", "utility", "manufacturer"], "excluded_with": []}', 'active', '2023-01-01', '2032-12-31', 'tax_credit', ARRAY['Verify census tract eligibility', 'Install qualifying charger', 'File IRS Form 8911 with tax return'], 'https://www.irs.gov/credits-deductions/alternative-fuel-vehicle-refueling-property-credit', 'https://www.irs.gov');
